# TODO: Currently session cookie and csrf token are a bit hard to get; One should get them from browser and store them 
# in external_services/leetcode_config.py; then they can be fetched from there
# guide on how to fetch them from browser: https://github.com/joshcai/leetcode-sync/blob/master/README.md - point 1.

# Better one: 
# Log in leetcode.com in chrome.
# Open chrome developer tools (F12)
# Click application.
# Expand storage->cookies.
# Copy and paste csrftoken and LEETCODE_SESSION.

LEETCODE_SESSION = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiOTQyNDE0MSIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImRqYW5nby5jb250cmliLmF1dGguYmFja2VuZHMuTW9kZWxCYWNrZW5kIiwiX2F1dGhfdXNlcl9oYXNoIjoiNjJmMWUwMjJmZWNjYTBhNGNjOWY1OGMzODU2MDQxNzA0ZThjYWQ2ZTk0MzdkZmE4ZjFiN2Y3ZTFmNTA5OTgwZSIsInNlc3Npb25fdXVpZCI6IjdlZDAzZTQ1IiwiaWQiOjk0MjQxNDEsImVtYWlsIjoic3RlZmFuLmtyc3Rlc2tpQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiU0tyc3Rlc2siLCJ1c2VyX3NsdWciOiJTS3JzdGVzayIsImF2YXRhciI6Imh0dHBzOi8vYXNzZXRzLmxlZXRjb2RlLmNvbS91c2Vycy9kZWZhdWx0X2F2YXRhci5qcGciLCJyZWZyZXNoZWRfYXQiOjE3Mzg0NDQxNTcsImlwIjoiMTI4LjE3OS4yNTQuMTI1IiwiaWRlbnRpdHkiOiI1MDA0MTk2M2FlNTYxY2ZhYmU5MjI1ZWRmZjM1YjE4ZiIsImRldmljZV93aXRoX2lwIjpbImQ1MzJhZmU2NjZiNjRiYzI3NGFiMTY0OWUzM2UyNjg0IiwiMTI4LjE3OS4yNTQuMTI1Il0sIl9zZXNzaW9uX2V4cGlyeSI6MTIwOTYwMH0.r8VzSC9Ot4vFubUIWZDtXRnF6XYesYV-Uu-2mBvHVJ8"
CSRF_TOKEN = "cQhssQUzqhYXMn3UkuUG8RBDgwUjjixtuE5wxAP68PVjYGpITDkkHoenzsmPpCOX"



